SDK7: tools and drivers

diff --git a/release/src-rt-7.x.main/src/cfe/build/broadcom/bcm947xx/compressed/Makefile b/release/src-rt-7.x.main/src/cfe/build/broadcom/bcm947xx/compressed/Makefile
--- a/release/src-rt-7.x.main/src/cfe/build/broadcom/bcm947xx/compressed/Makefile
+++ b/release/src-rt-7.x.main/src/cfe/build/broadcom/bcm947xx/compressed/Makefile
@@ -106,18 +106,44 @@ dep:
 cfez.bin: cfez
 	$(OBJCOPY) $< $@
 	$(OBJCOPYSREC) $< cfez.srec
+
+ifeq ($(DSLAC68U), 1)
+ifeq ($(JDM), 1)
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_dsl-ac68u_jdm.bin -s 00 dsl-ac68u_jdm_nvram.txt
+	cp cfe_dsl-ac68u_jdm.bin ../../../..
+else
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_dsl-ac68u.bin -s 00 dsl-ac68u_nvram.txt
+	cp cfe_dsl-ac68u.bin ../../../..
+endif
+endif
+
+ifeq ($(RTAC3200), 1)
+ifeq ($(EU), 1)
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac3200.bin -s 00 rt-ac3200_nvram_eu.txt
+else
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac3200.bin -s 00 rt-ac3200_nvram.txt
+endif
+	cp cfe_rt-ac3200.bin ../../../..
+endif
+
 ifeq ($(RTAC87U), 1)
 	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac87u.bin -s 00 rt-ac87u_nvram.txt
 	cp cfe_rt-ac87u.bin ../../../..
 	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
 		if [ "`wc -c < cfe_rt-ac87u.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
 			echo "*** ERROR *** : cfe_rt-ac87u.bin bootrom image size: `wc -c < cfe_rt-ac87u.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
 		fi ; \
 	fi
-else
+endif
+
 ifeq ($(RTAC68U), 1)
 ifeq ($(PATYPE), 0)
+ifeq ($(TMO), 1)
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac68u.bin -s 00 rt-ac68u_nvram_tmo.txt
+else
 	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac68u.bin -s 00 rt-ac68u_nvram.txt
+endif
 	cp cfe_rt-ac68u.bin ../../../..
 else ifeq ($(PATYPE), 5023)
 	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac68u_v2_5023.bin -s 00 rt-ac68u_v2_5023_nvram.txt
@@ -125,37 +151,65 @@ else ifeq ($(PATYPE), 5023)
 else ifeq ($(PATYPE), 85402)
 	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac68u_v2_85402.bin -s 00 rt-ac68u_v2_85402_nvram.txt
 	cp cfe_rt-ac68u_v2_85402.bin ../../../..
+else ifeq ($(PATYPE), 5003)
+	../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac68u_v2_5003.bin -s 00 rt-ac68u_v2_5003_nvram.txt
+	cp cfe_rt-ac68u_v2_5003.bin ../../../..
 endif
-else
+endif
+
 ifeq ($(RTN18U), 1)
 		../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-n18u.bin -s 00 rt-n18u_nvram.txt
 		cp cfe_rt-n18u.bin ../../../..
-else
+endif
+
+ifeq ($(RTAC56U), 1)
 		../../../../../ctools/nvserial -i cfez.bin -o cfe_rt-ac56u.bin -s 00 rt-ac56u_nvram.txt
 		cp cfe_rt-ac56u.bin ../../../..
 endif
+
+ifeq ($(DSLAC68U), 1)
+	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
+		if [ "`wc -c < cfe_dsl-ac68u.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
+			echo "*** ERROR *** : cfe_dsl-ac68u.bin bootrom image size: `wc -c < cfe_dsl-ac68u.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
+		fi ; \
+	fi
 endif
+
+ifeq ($(RTAC3200U), 1)
+	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
+		if [ "`wc -c < cfe_rt-ac3200.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
+			echo "*** ERROR *** : cfe_rt-ac3200.bin bootrom image size: `wc -c < cfe_rt-ac3200.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
+		fi ; \
+	fi
+endif
+
 ifeq ($(RTAC68U), 1)
 	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
 		if [ "`wc -c < cfe_rt-ac68u.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
 			echo "*** ERROR *** : cfe_rt-ac68u.bin bootrom image size: `wc -c < cfe_rt-ac68u.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
 		fi ; \
 	fi
-else
+endif
+
 ifeq ($(RTN18U), 1)
 	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
 		if [ "`wc -c < cfe_rt-n18u.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
 			echo "*** ERROR *** : cfe_rt-n18u.bin bootrom image size: `wc -c < cfe_rt-n18u.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
 		fi ; \
 	fi
-else
+endif
+
+ifeq ($(RTAC56U), 1)
 	@if [ "$(CFEZ_MAXSIZE)" != "" ]; then \
 		if [ "`wc -c < cfe_rt-ac56u.bin`" -gt "$(CFEZ_MAXSIZE)" ]; then \
 			echo "*** ERROR *** : cfe_rt-ac56u.bin bootrom image size: `wc -c < cfe_rt-ac56u.bin` exceeds limit: $(CFEZ_MAXSIZE)"; \
+			exit 2; \
 		fi ; \
 	fi
-endif
-endif
 endif
 
 # Link the loader and the kernel binary together
